lava_log_parser: use Unicode for HTML format strings
Use Unicode for the HTML format strings so that Unicode log lines can
get decoded correctly, rather than failing with the `ascii` default
codec.

The error below was seen with this log line which contains a Unicode
"copyright" symbol:

  <6>jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.

  [   ERROR/MainThread] 'ascii' codec can't encode character u'\xa9' in position 36: ordinal not in range(128)
  Traceback (most recent call last):
    File "/home/gtucker/project/kernelci/kernelci-backend/app/utils/callback/lava.py", line 609, in add_tests
      _add_test_log(meta, job_data["log"], plan_name)
    File "/home/gtucker/project/kernelci/kernelci-backend/app/utils/callback/lava.py", line 309, in _add_test_log
      utils.lava_log_parser.run(log, meta, txt, html)
    File "/home/gtucker/project/kernelci/kernelci-backend/app/utils/lava_log_parser.py", line 150, in run
      log_buffer.append(timestamp + fmt.format(msg_escape))
  UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 36: ordinal not in range(128)

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>